M48
; DRILL file {KiCad (6.0.1)} date Wed Nov  9 23:00:38 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-09T23:00:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.251
%
G90
G05
T1
X3.5Y-3.5
X3.5Y-52.5
X81.5Y-3.5
X81.5Y-52.5
T2
X13.716Y-48.591
X25.146Y-48.591
X36.83Y-48.514
X48.26Y-48.514
X59.69Y-48.514
X71.12Y-48.514
T0
M30
